version: '3.7'

services:
  mysql:
    build:
      context: ./MySql
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - radius_network
    ports:
      - "3307:3306"
    volumes:
      - radius_data:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=mysqladmin
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=radmin

  radius:
    build:
      context: ./Freeradius
      dockerfile: Dockerfile
    restart: on-failure:3
    ports:
      - "1812-1813:1812-1813/udp"
    networks:
      - radius_network
    environment:
      - DB_NAME=radius
      - DB_HOST=mysql
      - DB_USER=radius
      - DB_PASS=radmin
      - DB_PORT=3306
      - RADIUS_KEY=radclient
      #- RAD_CLIENTS=10.0.0.0/22
      - RAD_DEBUG=yes
    volumes:
      - radius_data:/sqlscripts
    depends_on:
      - mysql
    environment:
        DB_HOST: mysql
    links:
      - mysql

  admin:
    build:
      context: ./SimpleAdmin
      dockerfile: Dockerfile
    restart: on-failure:50
    ports:
      - "5000:5000"
    networks:
      - radius_network
    depends_on:
      - mysql
    links:
     - mysql
    environment:
        DB_HOST: mysql

networks:
  radius_network:

volumes:
  radius_data: